### ISSUE TITLE
Binaries shouldn't be stored in git

### ISSUE THREAD

**Issue by d-513** [powenn/AltServer-LinuxGUI#4]
Hey, seems that this is bundling AltServer-Linux. I would recommend downloading binaries in the script and adding to .gitignore, as this really makes the download slower and harder for packages. Thanks!

**Comment by powenn** [comment]
> Hey, seems that this is bundling AltServer-Linux. I would recommend downloading binaries in the script and adding to .gitignore, as this really makes the download slower and harder for packages. Thanks!
> 
> 
> 
> 

I will do that in next update(when iOS 15 fix)
