### ISSUE TITLE
Add instructions for manjaro/arch installation

### ISSUE THREAD

**Issue by TimestaticYT** [powenn/AltServer-LinuxGUI#5]

**Comment by powenn** [comment]
Already wrote in readme,use dpkg

**Comment by TimestaticYT** [comment]
I just got confused because I thought that it would be another way to install it on debian because I thought .deb files can only be installed on debian. Would be a neat improvement if you mentioned more clearly that the dpkg install is for arch. Thanks for doing this project tho, because it only made altserver on linux viable for me
